export {default as Hero} from './Hero'
export {default as Features} from './Features'
export {default as NavBar} from './NavBar'
export {default as Services} from './Services'
export {default as Tech} from './Tech'
export {default as Pricing} from './Pricing'
